### ISSUE TITLE
Napisati instrukcije za pokretanje produkcije

### ISSUE THREAD

**Issue by aheacon** [aheacon/school_enrollment_frontend#57]
- Buduci da kontejneri ne rade, moramo pokrenuti ono sto radi -  a to je lokalno (backend moze biti kontejner).
- Radimo na produkcijskom serveru i sve instaliramo od pocetka.
- Zelimo produkcijski build
- `npm run dev` radi normalno, a mi zelimo expose port preko build binary
- Zelimo da za deploymnet izvrsimo:
```bash
$ $ HOST='0.0.0.0' PORT=3535 npm start 
```
- Ova komanda zahtjeva produkcijski build.
- Na produkciji ja sam instalirao `node 20` (dodati kasnije instrukcije kako instalirati preko gpg key i/ili  koristenje `nvm`)

- Sada mi treba da se doda u `Readme.md` upustvo kako:
1. kako pokrenuti `yarn` preko `corepackage`
2. kompajlirati i pokrenuti build package

- Kao pocetak koristiom sam `Docker` file,koji radi preko `yarn`, ali meni trenutno na produkcijskom serveru (Ubunutu 22.04)  ti koraci ne rade (jer je Docker image optimizovan za node).
- Ovo su koraci koje sam uradio i zapeo sam na instalaciji preko`yarn`.
- Takodjer probao sam i `next build`, ali ni to mi nije radilo.
- Koraci:
```bash
$ corepack enable
$ corepack prepare yarn@stable --activate
$ yarn --version
! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@4.2.2+sha512.c44e283c54e02de9d1da8687025b030078c1b9648d2895a65aab8e64225bfb7becba87e1809fc0b4b6778bbd47a1e2ab6ac647de4c5e383a53a7c17db6c3ff4b.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager

5.2.2

# Install packages - error
$ yarn install --frozen-lockfile
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @headlessui/react@npm:1.7.7, @heroicons/react@npm:2.0.13, and 471 more.
➤ YN0000: └ Completed in 6s 511ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 6s 633ms

# Build production binary
$ NODE_ENV=production
$ yarn build
Internal Error: school_enrollment_frontend@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at Xx.getCandidates (/home/anel/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:205:8149)
    at Pd.getCandidates (/home/anel/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:141:1311)
    at /home/anel/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:210:8409
    at Ky (/home/anel/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:140:53916)
    at Fe (/home/anel/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:210:8389)
    at async Promise.allSettled (index 0)
    at async _c (/home/anel/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:140:53244)
    at async /home/anel/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:210:9140
    at async Qi.startProgressPromise (/home/anel/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:140:137284)
    at async St.resolveEverything (/home/anel/.cache/node/corepack/v1/yarn/4.2.2/yarn.js:210:7138)
```
- Probao sam da izbrisem `package-lock.json` i ponovo da idem na korak instaliranja
```bash
$  yarn install --frozen-lockfile
➤ YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead

➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @headlessui/react@npm:1.7.7, @heroicons/react@npm:2.0.13, and 471 more.
➤ YN0000: └ Completed in 2s 812ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
➤ YN0000: └ Completed
➤ YN0000: · Failed with errors in 2s 918ms
``` 
- `package.json` na produkciji
```bash
$ cat package.json 
{
  "name": "school_enrollment_frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.7",
    "@heroicons/react": "^2.0.13",
    "@react-pdf/renderer": "^3.4.4",
    "axios": "^1.2.1",
    "js-cookie": "^3.0.1",
    "jspdf": "^2.5.1",
    "next": "^14.2.3",
    "next-auth": "^4.18.9",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.41.1",
    "react-icons": "^5.2.1",
    "react-toastify": "^9.1.1"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.13",
    "eslint": "8.30.0",
    "eslint-config-next": "13.1.1",
    "postcss": "^8.4.20",
    "tailwindcss": "^3.2.4"
  },
  "packageManager": "yarn@4.2.2+sha512.c44e283c54e02de9d1da8687025b030078c1b9648d2895a65aab8e64225bfb7becba87e1809fc0b4b6778bbd47a1e2ab6ac647de4c5e383a53a7c17db6c3ff4b"
}
```

**Comment by Faariis** [comment]
@aheacon @IsmetGlumcevic 
Ovo je za windows:

1. Skinuti nvm.setup.exe, onda:
nvm install 20
nvm use 20
node -v
Kod mene je: v20.13.1
2. corepack enable
3. corepack prepare yarn@stable --activate
4. yarn set version latest - ja sam ovo uradio jer -immutable ne radi
5. Trebala bi ova komanda: yarn install --immutable, ona ustvari provjerava da li se yarn.lock mijenja ali yarn.lock mora se promijenit tako da neće raditi pa mora se koristiti: yarn install
6. set NODE_ENV=production
7. yarn build
8. $env:PORT=3535; $env:HOSTNAME="0.0.0.0"; node .next/standalone/server.js

Za linux:
export PORT=3535
export HOSTNAME="0.0.0.0"
node .next/standalone/server.js

![Screenshot (385)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/5947f072-c77f-479a-8cf1-b90c4c0e050e)
![Screenshot (386)](https://github.com/aheacon/school_enrollment_frontend/assets/84626163/16dee90d-88f1-440a-bc39-fbf9c7a37389)

**Comment by aheacon** [comment]
Mislim da bi ovo trebala biti sekvenca (nisam jos probao, ko prije stigne nek javi :) ):
1. Napraviti direktorij <cache>
2. Kopiraj package.json iz <source> (ovdje treba vidjeti treba li sta izbaciti) , i yarn.lock (ako ima) u taj direktorij
3. Podesiti  `yarn config set cache-folder <ime_direktorija>/.yarn`
4. Napraviti i otic  na novi folder `<production/>`
5. Pokreni `NODE_ENV=production yarn install`
6. Kopirati sve nase dokumente u `<production>` folder
7. Pokrenuti `yarn install && yarn build`
8. Startaj server: `HOST='0.0.0.0' PORT=3535 npm start ` ili `yarn serve`

**Comment by aheacon** [comment]
Proradilo mi je ovo lokalno - radi sa lokalnim pokretanjem frontenda i backend dockerom.
```bash
$ HOST='0.0.0.0' PORT=3535 npm start

> school_enrollment_frontend@0.1.0 start
> next start

  ▲ Next.js 14.2.3
  - Local:        http://localhost:3535

 ✓ Starting...
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
 ✓ Ready in 731ms
```

- Proradilo nam je i na produkciji - ali iz nekog razloga ne cita podatke  sa backend kontejnera .
- Provjerio sam podake fixture radi i podaci su u bazi.
- Evo upustvo, @Faariis  probaj i ti i vidi zadnji patch na backendu, sta bih trebao nastimati.
```bash
# Make node modules in cache folder
$ cp package.json  yarn.lock ../cache_frontend/

# Make sure yarn is configured and set (with nodejs 20)
$ yarn --version
4.2.2

# Install node modules
$ yarn install

# Copy modules to source directory
$ cp node_modules/ ../school_enrollment_frontend/


# Problems on production (small RAM)
$ yarn install 
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @headlessui/react@npm:1.7.7, @heroicons/react@npm:2.0.13, and 471 more.
➤ YN0000: └ Completed in 4s 82ms
➤ YN0000: ┌ Fetch step
➤ YN0000: ⠇ =========================-------------------------------------------------------
Killed

# Solved with
$ sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
$ sudo /sbin/mkswap /var/swap.1
$ sudo /sbin/swapon /var/swap.1

# Result
$ ls
node_modules  package.json  yarn.lock

# Move to source directory
$ cp -r node_modules/ ../school_enrollment_frontend/

# Go to source directory
$ cd ../school_enrollment_frontend

# Install as build environment (maybe I should do that in earlir step) - 2 time building
$ NODE_ENV=production yarn install && yarn run build

# Check backend is running
$ docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
674df57004d7   nginx:latest                "/docker-entrypoint.…"   45 seconds ago   Up 10 seconds             0.0.0.0:3500->80/tcp, :::3500->80/tcp       nginx-cnt
501a51d82985   docker-enrollment_backend   "/bin/sh ./entrypoin…"   45 seconds ago   Up 12 seconds (healthy)   0.0.0.0:3534->3500/tcp, :::3534->3500/tcp   myenrollment-cnt
3a2e32a3a085   docker-mariadb              "docker-entrypoint.s…"   45 seconds ago   Up 42 seconds (healthy)   3306/tcp                                    mariadb-cnt
c16a511a4c85   amir20/dozzle:latest        "/dozzle"                45 seconds ago   Up 42 seconds             0.0.0.0:9999->8080/tcp, :::9999->8080/tcp   dozzle
# Start the server
$ HOST='0.0.0.0' PORT=3535 npm start
```

- Na produkciji frontend radi (cak i autorizacija), ali ne cita defaultne podatke iz fixture
http://151.115.72.222:3535/

- Trebalo bi dodati `npm stop`
```bash
# Trenutno se 
$ netstat -nap |grep 3535
$ kill -9 <pid>
```

**Comment by aheacon** [comment]
- Ovo je promjena na frontendu
```diff
$ git diff
diff --git a/.env b/.env
index ee43a92..31cc975 100644
--- a/.env
+++ b/.env
@@ -1,7 +1,8 @@
 # Backend
 # port 3500 will be used later as reverse proxy
 #NEXT_PUBLIC_URL=http://51.15.114.199:3534/
-NEXT_PUBLIC_URL=http://localhost:3500/
+#NEXT_PUBLIC_URL=http://151.115.72.222:3500/
+NEXT_PUBLIC_URL=http://localhost:3534/
```

- Ovo je promjena na backendu
```diff
$ git diff
diff --git a/myEnrollment/myEnrollment/settings.py b/myEnrollment/myEnrollment/settings.py
index 0e60b37..6b74094 100644
--- a/myEnrollment/myEnrollment/settings.py
+++ b/myEnrollment/myEnrollment/settings.py
@@ -30,13 +30,13 @@ DEBUG = os.environ.get("DJANGO_DEBUG") == "True"
 # if os.environ.get('DJANGO_ALLOWED_HOSTS'):
 #     ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS').split(',')
 
-#if os.environ["ENV_DOCKER_RUNTIME"] == "1":
+if os.environ["ENV_DOCKER_RUNTIME"] == "1":
     # ENV_WEB_APP_ALLOWED_HOSTS
-#    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
-#else:
-#    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "51.15.114.199"]
+    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "151.115.72.222"]
+else:
+    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "51.15.114.199", "151.115.72.222"]
 
-ALLOWED_HOSTS = ["*"]
+# ALLOWED_HOSTS = ["*"]
 # If changed ENV_NGINX_PORT for docker, change port here
 CSRF_TRUSTED_ORIGINS = [
     # Add name of Docker service
@@ -48,6 +48,9 @@ CSRF_TRUSTED_ORIGINS = [
     "http://localhost:3535",
     "http://127.0.0.1:3500",
     "http://127.0.0.1:3535",
+    "http://151.115.72.222:3535",
+    "http://151.115.72.222:3000",
+    "http://151.115.72.222:3500",
 ]
```

- Ovo je izgleda novi problem sa GoogleChromom
https://stackoverflow.com/questions/70635646/request-blocked-by-cors-policy-the-request-client-is-not-a-secure-context-and-t
- Ovo je greska
```bash
151.115.72.222/:1 Access to fetch at 'http://localhost:3500/api/sec-students/student-list/1/all-courses/' from origin 'http://151.115.72.222:3535' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `local`.
```
- Nastimano je `CORS_ORIGIN_ALLOW_ALL = True`
- Nakon promjene `.env` u frontendu, treba ponoviti `yarn build && HOST='0.0.0.0' PORT=3535 npm start`.
- Sad je sve proradilo hvala Bogu.

http://151.115.72.222:3535/

**Comment by aheacon** [comment]
Evo upustvo za `systemd` skriptu @Faariis  molim te dodaj sve ove instrukcije u `Deploy.md` file i napravi molim te PR.
- First check if server is already running locally on the port 3535
```bash
$ sudo netstat -nap|grep 3535
tcp6       0      0 :::3535                 :::*                    LISTEN      505033/next-server 
# kill it
$ kill -9 505033
```
- Create `systemd` script

Add in /etc/systemd/system/myenrollment_frontend.service
```bash
[Unit]
Description=My Frontend Enrollment Application
After=network.target

[Service]
# User and group to run the service as
User=anel
Group=anel

# The working directory where your application is located
WorkingDirectory=/home/anel/GitHub/school_enrollment_frontend

# Command to start your application
ExecStart=/usr/bin/npm start

# Environment variables
Environment=HOST=0.0.0.0
Environment=PORT=3535

# Restart settings
Restart=always
RestartSec=10

# Output logs to syslog
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=myfrontend

[Install]
WantedBy=multi-user.target
```
- Execute
```bash
$ sudo systemctl daemon-reload
$ sudo systemctl enable myenrollment_frontend.service
$ sudo systemctl start myenrollment_frontend.service
$ sudo systemctl status myenrollment_frontend.service 
$ sudo systemctl status myenrollment_frontend.service
● myenrollment_frontend.service - My Frontend Enrollment Application
     Loaded: loaded (/etc/systemd/system/myenrollment_frontend.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2024-05-26 10:12:46 UTC; 20s ago
   Main PID: 509068 (npm start)
      Tasks: 23 (limit: 1095)
     Memory: 46.8M
        CPU: 800ms
     CGroup: /system.slice/myenrollment_frontend.service
             ├─509068 "npm start" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             ├─509079 sh -c "next start"
             └─509080 "next-server (v14.2.3)" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ">

May 26 10:12:46 scw-amazing-maxwell systemd[1]: Started My Frontend Enrollment Application.
May 26 10:12:46 scw-amazing-maxwell myfrontend[509068]: > school_enrollment_frontend@0.1.0 start
May 26 10:12:46 scw-amazing-maxwell myfrontend[509068]: > next start
May 26 10:12:46 scw-amazing-maxwell myfrontend[509080]:   ▲ Next.js 14.2.3
May 26 10:12:46 scw-amazing-maxwell myfrontend[509080]:   - Local:        http://localhost:3535
May 26 10:12:46 scw-amazing-maxwell myfrontend[509080]:  ✓ Starting...
May 26 10:12:46 scw-amazing-maxwell myfrontend[509080]:  ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
May 26 10:12:46 scw-amazing-maxwell myfrontend[509080]:  ✓ Ready in 439ms
```
- Check logs
```bash
$ sudo journalctl -u myenrollment_frontend.service
```
